// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Context;

#nullable disable

namespace WebAPI.Migrations
{
    [DbContext(typeof(PassagemDbContext))]
    [Migration("20221106193549_PrimaryMigration")]
    partial class PrimaryMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebAPI.Models.Passagem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("data");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("VARCHAR(255)")
                        .HasColumnName("destino");

                    b.Property<string>("Horario")
                        .IsRequired()
                        .HasColumnType("VARCHAR(20)")
                        .HasColumnName("horario");

                    b.HasKey("Id");

                    b.ToTable("passagens");
                });
#pragma warning restore 612, 618
        }
    }
}
